full_stack_lecture/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'herbs' => 'herb#index' , as: 'herbs'

  # new needs to be first because is more specific
  get 'herb/new' => 'herb#new', as: 'new_herb'

  get 'herb/:id' => 'herb#show', as: 'herb'

  # no alias, it's subnit button and database
  post 'herbs' => 'herb#create'

  delete 'herb/:id' => 'herb#destroy', as: 'delete_herb'

  # alias for the routes 

  get 'herb/:id/edit' => 'herb#edit', as: 'edit_herb'

  patch 'herb/:id' => 'herb#update'

end

full_stack_lecture/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

full_stack_lecture/app/models/herb.rb
class Herb < ApplicationRecord




    
end

full_stack_lecture/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

full_stack_lecture/app/controllers/herb_controller.rb
class HerbController < ApplicationController

    def index
        @herbs = Herb.all
    end

    def show
        @herb = Herb.find(params[:id])
    end

    def new
        @herb = Herb.new
    end


    # strong params needed and it doesn't need a view
    def create 
        @herb = Herb.create(herb_params)
            if @herb.valid?
            redirect_to herbs_path
            else
            redirect_to new_herb_path      
            end
    end

    # mode_params is a convention
    # params.require(model_name.permit(:column_name, :column_name))
    def herb_params
        params.require(:herb).permit(:name, :is_watered)
    end


    def destroy
        @herb = Herb.find(params[:id])
        if @herb.destroy
            redirect_to herbs_path  
        else
            redirect_to herb_path(@herb)
        end
    end


    def edit
        @herb = Herb.find(params[:id])
    end

    def update
        @herb = Herb.find(params[:id])
        @herb.update(herb_params)
        if @herb.valid?
            redirect_to herbs_path(@herb)  
        else
            redirect_to edit_herb_path(@herb)
        end

    end

end

full_stack_lecture/app/helpers/application_helper.rb
module ApplicationHelper
end

full_stack_lecture/app/helpers/herb_helper.rb
module HerbHelper
end

full_stack_lecture/app/views/herb/edit.html.erb
<h1>  Edit an  herb </h1>


                 <%# difference with new is the methodf patch %>
<%= form_with model: @herb, local: true, method: :patch do |form| %>

<%= form.label :name %>
<br />
<%= form.text_field :name %>
<br />
<br />

<%= form.radio_button :is_watered, 'yes' %>
<%= form.label :is_watered, 'Herb is watered' %>
<br />
<%= form.radio_button :is_watered, 'no' %>
<%= form.label :is_watered, 'Herb is NOT watered' %>
<br />
<br />
<%= form.submit 'Update Herb' %>

<% end %>


<br />
<%= link_to 'Back to all herbs', herbs_path %>

full_stack_lecture/app/views/herb/index.html.erb
<h1> Herb Garden </h1>


<ul>

<%#  = signonly in what I want to show not all the embedded code  %>
    <% @herbs.each do |herb| %>
    <li>  <%= link_to herb.name , 
    herb_path(herb)  %> </li>
    <% end %>

</ul>


<br />


<%= link_to 'Add a new herb', new_herb_path %>

full_stack_lecture/app/views/herb/new.html.erb
<h1>  Create a new herb </h1>

<%#  %>

<%= form_with model: @herb, local: true do |form| %>

<%= form.label :name %>
<br />
<%= form.text_field :name %>
<br />
<br />

<%= form.radio_button :is_watered, 'yes' %>
<%= form.label :is_watered, 'Herb is watered' %>
<br />
<%= form.radio_button :is_watered, 'no' %>
<%= form.label :is_watered, 'Herb is NOT watered' %>
<br />
<br />
<%= form.submit 'Add Herb' %>

<% end %>

<%= link_to 'Back to all herbs', herbs_path %>

full_stack_lecture/app/views/herb/show.html.erb
<h1><%= @herb.name %></h1>

<p>   Is watered? <%= @herb.is_watered%>  </p>

<br/>
<%= link_to 'Delete herb', delete_herb_path(@herb), method: :delete %>
<br/>





<%= link_to 'Back to all herbs', herbs_path %>

<br/>

<%= link_to 'Edit herb', edit_herb_path %>

full_stack_lecture/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>